### ISSUE TITLE
Consultation and consultation

### ISSUE THREAD

**Issue by LJW0306** [LiangZhang1996/Advanced_XLight#1]

**Comment by SilenceWinter** [comment]
> Hello, I am also a researcher in the field of transportation. I am very interested in your work. Can you give me your WeChat or other contact information? I would like to discuss more privately with you. If it's not convenient, you can also add my wx: Ljw_ 0306

Hi， where can I get the data json field description？

**Comment by SilenceWinter** [comment]
> Hello, I am also a researcher in the field of transportation. I am very interested in your work. Can you give me your WeChat or other contact information? I would like to discuss more privately with you. If it's not convenient, you can also add my wx: Ljw_ 0306

Hi， where can I get the data json field description？

**Comment by LiangZhang1996** [comment]
@LJW0306  your wechat account is invalid, please check it.

**Comment by LJW0306** [comment]
***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiangZhang1996/Advanced_XLight"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 晚上7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiangZhang1996/Advanced_XLight] Consultation and consultation (Issue #1)





 
@LJW0306  your wechat account is invalid, please check it.

**Comment by LiangZhang1996** [comment]
?

**Comment by LiangZhang1996** [comment]
![IMG_3626](https://github.com/LiangZhang1996/Advanced_XLight/assets/43574084/1056e873-5e0a-4863-b6fa-6229894aa71c)
